Repository team-devOops/moiming, pull requests merged in 2023-08, with the labels that each got.

#2 chore: MMG-7 JPA 설정하기
  build.gradle
  src/main/resources/application.yml
Labels: 🏭 config

#4 MMG-8-Swagger세팅
  build.gradle
  src/main/resources/application.yml
  src/main/resources/config/swagger-config.yml
Labels: 🏭 config

#3 chore: MMG-9 JPA 로깅 설정하기
  src/main/resources/application.yml
Labels: 🏭 config

#5 docs: MMG-19 PR TEMPLATE 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🏭 config

#6 feat: 모임 관련 엔티티 생성
  src/main/java/com/moiming/core/Flag.java
  src/main/java/com/moiming/meet/domain/MeetInfo.java
  src/main/java/com/moiming/meet/domain/MeetJoinUser.java
Labels: 🧩 add

#7 feat: MMG-13 모임생성 컨트롤러 생성
  build.gradle
  src/main/java/com/moiming/meet/web/MeetsController.java
Labels: 🧩 add

#9 feat: MMG-13 모임생성 기능 생성
  src/main/java/com/moiming/core/BaseControllerAdvice.java
  src/main/java/com/moiming/core/InvalidResponse.java
  src/main/java/com/moiming/meet/application/MeetInfoService.java
  src/main/java/com/moiming/meet/domain/MeetInfo.java
  src/main/java/com/moiming/meet/dto/MeetCreateRequest.java
  src/main/java/com/moiming/meet/dto/MeetValidateMessage.java
  src/main/java/com/moiming/meet/infra/MeetInfoRepository.java
  src/main/java/com/moiming/meet/web/MeetsController.java
  src/test/java/com/moiming/meet/application/MeetInfoServiceTest.java
  src/test/java/com/moiming/meet/domain/MeetCreateRequestTest.java
  src/test/java/com/moiming/meet/infra/MeetInfoRepositoryTest.java
  src/test/java/com/moiming/meet/web/MeetsControllerTest.java
Labels: 🧩 add

#10 feat: MMG-11 모임생성 api 개발
  build.gradle
  src/main/java/com/moiming/core/BaseControllerAdvice.java
  src/main/java/com/moiming/core/Flag.java
  src/main/java/com/moiming/core/InvalidResponse.java
  src/main/java/com/moiming/meet/application/MeetInfoService.java
  src/main/java/com/moiming/meet/domain/MeetInfo.java
  src/main/java/com/moiming/meet/domain/MeetJoinUser.java
  src/main/java/com/moiming/meet/dto/MeetCreateRequest.java
  src/main/java/com/moiming/meet/dto/MeetValidateMessage.java
  src/main/java/com/moiming/meet/infra/MeetInfoRepository.java
  src/main/java/com/moiming/meet/web/MeetsController.java
  src/test/java/com/moiming/meet/application/MeetInfoServiceTest.java
  src/test/java/com/moiming/meet/domain/MeetCreateRequestTest.java
  src/test/java/com/moiming/meet/infra/MeetInfoRepositoryTest.java
  src/test/java/com/moiming/meet/web/MeetsControllerTest.java
Labels: ✨ feat

#11 feat: MMG-21 JPA Auditing 설정
  src/main/java/com/moiming/core/jpa/BaseEntity.java
  src/main/java/com/moiming/core/jpa/JpaConfig.java
  src/main/java/com/moiming/meet/domain/MeetInfo.java
  src/main/java/com/moiming/meet/domain/MeetJoinUser.java
  src/main/java/com/moiming/meet/dto/MeetCreateRequest.java
Labels: 🏭 config

#12 feat: MMG-25 모임 단건 조회 api 생성
  src/main/java/com/moiming/core/BaseControllerAdvice.java
  src/main/java/com/moiming/core/exception/CustomNoResultException.java
  src/main/java/com/moiming/core/exception/MoimingException.java
  src/main/java/com/moiming/meet/application/MeetInfoService.java
  src/main/java/com/moiming/meet/domain/MeetInfo.java
  src/main/java/com/moiming/meet/dto/MeetCreateRequest.java
  src/main/java/com/moiming/meet/dto/MeetInfoResponse.java
  src/main/java/com/moiming/meet/web/MeetsController.java
  src/test/java/com/moiming/meet/application/MeetInfoServiceTest.java
  src/test/java/com/moiming/meet/infra/MeetInfoRepositoryTest.java
  src/test/java/com/moiming/meet/web/MeetsControllerTest.java
Labels: ✨ feat

#13 docs: gradle.yml 생성
  .github/workflows/gradle.yml
  src/main/java/com/moiming/meet/dto/MeetCreateRequest.java
  src/test/java/com/moiming/meet/dto/MeetCreateRequestTest.java
Labels: 🏭 config

#14 feat: MMG-24 모임 삭제 api 생성
  src/main/java/com/moiming/meet/application/MeetInfoService.java
  src/main/java/com/moiming/meet/domain/MeetInfo.java
  src/main/java/com/moiming/meet/domain/MeetJoinUser.java
  src/main/java/com/moiming/meet/dto/MeetCreateRequest.java
  src/main/java/com/moiming/meet/dto/MeetInfoResponse.java
  src/main/java/com/moiming/meet/web/MeetsController.java
  src/test/java/com/moiming/meet/application/MeetInfoServiceTest.java
  src/test/java/com/moiming/meet/domain/MeetInfoTest.java
  src/test/java/com/moiming/meet/infra/MeetInfoRepositoryTest.java
  src/test/java/com/moiming/meet/web/MeetsControllerTest.java
Labels: ✨ feat

#15 build: QueryDSL 설정 추가
  build.gradle
Labels: 🏭 config

#16 feat: MMG-26 모임 가입 api 생성
  src/main/java/com/moiming/meet/application/MeetJoinService.java
  src/main/java/com/moiming/meet/domain/Level.java
  src/main/java/com/moiming/meet/domain/MeetInfo.java
  src/main/java/com/moiming/meet/domain/MeetJoinUser.java
  src/main/java/com/moiming/meet/dto/MeetCreateRequest.java
  src/main/java/com/moiming/meet/dto/MeetInfoResponse.java
  src/main/java/com/moiming/meet/dto/MeetJoinRequest.java
  src/main/java/com/moiming/meet/dto/MeetValidateMessage.java
  src/main/java/com/moiming/meet/infra/MeetJoinUserRepository.java
  src/main/java/com/moiming/meet/web/MeetJoinController.java
  src/test/java/com/moiming/meet/application/MeetInfoServiceTest.java
  src/test/java/com/moiming/meet/application/MeetJoinServiceTest.java
  src/test/java/com/moiming/meet/domain/MeetCreateRequestTest.java
  src/test/java/com/moiming/meet/dto/MeetJoinRequestTest.java
  src/test/java/com/moiming/meet/web/MeetJoinControllerTest.java
  src/test/resources/application.yml
  src/test/resources/data.sql
Labels: ✨ feat, 🏭 config

#17 feat: MMG-30 모임 가입 정보 조회 api 생성
  src/main/java/com/moiming/core/BaseControllerAdvice.java
  src/main/java/com/moiming/meet/application/MeetJoinService.java
  src/main/java/com/moiming/meet/domain/Level.java
  src/main/java/com/moiming/meet/domain/MeetJoinUser.java
  src/main/java/com/moiming/meet/dto/MeetJoinRequest.java
  src/main/java/com/moiming/meet/dto/MeetJoinResponse.java
  src/main/java/com/moiming/meet/dto/MeetValidateMessage.java
  src/main/java/com/moiming/meet/web/MeetJoinController.java
  src/main/resources/application.yml
  src/test/java/com/moiming/meet/application/MeetJoinServiceTest.java
  src/test/java/com/moiming/meet/web/MeetJoinControllerTest.java
  src/test/resources/application.yml
Labels: ✨ feat, 🏭 config
